version: '3'
services:
  nginx:
    image: nginx:1.1
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - mypayments
      - bookmyjam
    networks:
      - net

  mypayments:
    image: getting2vinod/addpayment:1.1
    container_name: mypayments
    hostname: mypayments
    networks:
      - net
    environment:
     - APP_ROUTE=pay
    volumes:
      - ./json:/json
      - ./:/app
    entrypoint: "python /app/app.py"

  bookmyjam:
    image: getting2vinod/bookmyjam:1.0
    container_name: bookmyjam
    hostname: bookmyjam
    networks:
      - net
    volumes:
      - ../bookmyjam/json:/json
    environment:
     - APP_ROUTE=jam
    entrypoint: "python /app/app.py"

  pdfviewer:
    image: pdfviewerimage:latest
    container_name: pdfviewer
    hostname: pdfviewer
    networks:
      - net
    environment:
     - APP_ROUTE=pdf
    volumes:
      -  ../pdfviewer:/app
    entrypoint: "python app.py"

networks:
  app-network:
    driver: bridge
