version: '3'
services:
  nginx:
    image: nginx:1.27
    ports:
      - "80:80"
    depends_on:
      - mypayments
    networks:
      - net

  mypayments:
    image: getting2vinod/addpayment:1.1
    container_name: mypayments
    hostname: pay.myapp.localhost    
    networks:
      - net
    environment:
     - APP_ROUTE=pay
    volumes:
      - ./json:/json
      - ./:/app
    entrypoint: "python /app/app.py"

  bookmyjam:
    image: getting2vinod/bookmyjam:1.0
    container_name: bookmyjam
    hostname: bookmyjam    
    networks:
      - net
    volumes:
      - ./json:/json
    environment:
     - APP_ROUTE=jam
    entrypoint: "python /app/app.py"
  
  pdfviewer:
    image: pdfviewerimage:latest
    container_name: pdfviewer
    hostname: pdfviewer    
    networks:
      - net
    environment:
     - APP_ROUTE=pdf
    volumes:
      - ./:/app
    entrypoint: "python app.py"

networks:
  net:
    driver: bridge
    external: true
    
